### ISSUE TITLE
Failure on DAEDALUS.WAD

### ISSUE THREAD

**Issue by Kroc** [fragglet/wadptr#19] opened 2023-11-01 00:44 UTC
https://www.doomworld.com/idgames/themes/TeamTNT/daedalus/daedalus
```
Adding: BLOCKMAP       Stacking BLOCKMAP lump too short: 0 < 4 header size
```

**Comment by fragglet** [comment] 2023-11-02 08:52
Dupe of #17

**Closed as completed by fragglet** 2023-11-02 08:52 UTC
Labels: duplicate
