### ISSUE TITLE
Failure on Cryogenics.wad

### ISSUE THREAD

**Issue by Kroc** [fragglet/wadptr#18] opened 2023-10-31 22:32 UTC
https://www.doomworld.com/forum/topic/98149-cryogenics-a-small-collection-of-random-cl9-slaughterish-maps-now-on-idgames/
https://www.doomworld.com/idgames/levels/doom2/Ports/a-c/cryogenics
```
Adding: MAP01          Empty (0%).
Adding: THINGS         Storing (0%), done.
Adding: LINEDEFS       Deferred... (0%)
Adding: SIDEDEFS       Packing (62%), done.
Adding: VERTEXES       Storing (0%), done.
Adding: SEGS           Empty (0%).
Adding: SSECTORS       Empty (0%).
Adding: NODES          Storing (0%), done.
Adding: SECTORS        Storing (0%), done.
Adding: REJECT         Empty (0%).
Adding: BLOCKMAP       Stacking BLOCKMAP lump too short: 0 < 4 header size
```

**Comment by fragglet** [comment] 2023-11-02 08:52
Dupe of #17

**Closed as completed by fragglet** 2023-11-02 08:52 UTC
Labels: duplicate
