### ISSUE TITLE
Failure on EGYPT.WAD

### ISSUE THREAD

**Issue by Kroc** [fragglet/wadptr#23] opened 2023-11-04 08:36 UTC
I'm running wadptr through doomkid's "Big Vanilla Wad Pack"; 2.2 GB of vanilla and limit-removing WADs. You'll probably want to download this yourself and run through it -- just search inside the folder for EGYPT.WAD
https://www.doomworld.com/forum/topic/114671
```
Adding: PLATFORM       Squashing Column 0 overruns the end of the lump with no 0xff terminating byte
```
Even though I've seen this error message before, this is using the latest binary so perhaps is a different root cause?

**Comment by Kroc** [comment] 2023-11-04 08:51
NC_19.WAD & NEC_RAW.WAD
```
Adding: SKY1           Squashing Column 251 overruns the end of the lump with no 0xff terminating byte
```

**Comment by Kroc** [comment] 2023-11-04 08:58
AWSOPALE.WAD
```
Adding: PLATFORM       Squashing Column 0 overruns the end of the lump with no 0xff terminating byte
```

**Comment by Kroc** [comment] 2023-11-04 09:03
AWSOPALE.WAD, CARNAGE.WAD, CLASSIX.WAD, DIEHARD.WAD, DWANGO3/4/8.WAD, ENGINE.WAD, GOTCHA3.WAD, HOTECAL2.WAD, MANCERX/2/3.WAD, NM0001.WAD, REDROOM_.WAD, STALAG.WAD, SYMBOLIC.WAD & WATCH51.WAD
All ~~three~~ ~~four~~ ~~five~~ ~~six~~ ~~seven~~ ~~eight~~ ~~nine~~ ~~ten~~ ~~eleven~~ ~~twelve~~ ~~thirteen~~ ~~fourteen~~ ~~fifteen~~ ~~sixteen~~ ~~seventeen~~ eighteen appear to use the same lump!
```
Adding: PLATFORM       Squashing Column 0 overruns the end of the lump with no 0xff terminating byte
```

**Comment by Kroc** [comment] 2023-11-04 09:08
ENGINE.WAD
```
Adding: PLATFORM       Squashing Column 0 overruns the end of the lump with no 0xff terminating byte
```

**Comment by Kroc** [comment] 2023-11-04 12:23
Pass complete:
```
before: 3,629,386,491 bytes
after:  3,143,503,051 bytes
saved:    485,883,440 bytes
```

**Comment by fragglet** [comment] 2023-11-04 14:14
Dupe of #21 - now fixed, thanks!

**Closed as completed by fragglet** 2023-11-04 14:14 UTC
Labels: duplicate
